# -*- coding: utf-8 -*-
"""sebha_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVdZwKxPzU0_IigX_IdlzD9bULAqHI86
"""

import streamlit as st
import json
import os

SAVE_FILE = "sebha_web_counts.json"

# تحميل البيانات إن وجدت
def load_counts():
    if os.path.exists(SAVE_FILE):
        with open(SAVE_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {
        "سبحان الله": 0,
        "الحمد لله": 0,
        "الله أكبر": 0,
        "اللهم صل على محمد": 0,
        "لا إله إلا الله": 0,
    }

# حفظ البيانات
def save_counts(data):
    with open(SAVE_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f)

# -----------------------
st.set_page_config(page_title="مسبحة إلكترونية", page_icon="🕌", layout="centered")
st.title("🌙 مسبحة إلكترونية")

counts = load_counts()

# اللون الأخضر للتسبيح
button_style = """
    <style>
        .stButton > button {
            background-color: #28a745;
            color: white;
            height: 3em;
            font-size: 20px;
        }
        .stButton > button:hover {
            background-color: #218838;
        }
    </style>
"""
st.markdown(button_style, unsafe_allow_html=True)

# عرض العداد والأزرار لكل نوع
tasbeeh_list = ["سبحان الله", "الحمد لله", "الله أكبر", "اللهم صل على محمد", "لا إله إلا الله"]

for tasbeeh in tasbeeh_list:
    st.subheader(tasbeeh)
    cols = st.columns([2, 1])
    with cols[0]:
        st.markdown(f"<h1 style='text-align: center; color: #28a745;'>{counts[tasbeeh]}</h1>", unsafe_allow_html=True)
    with cols[1]:
        if st.button(f"تسبيح {tasbeeh}", key=tasbeeh):
            counts[tasbeeh] += 1
            save_counts(counts)
            st.rerun()

st.divider()

# زر إعادة الضبط
if st.button("🔄 إعادة الضبط"):
    for key in counts:
        counts[key] = 0
    save_counts(counts)
    st.rerun()